### ISSUE TITLE
Shifting arrows

### ISSUE THREAD

**Issue by HongTao628** [yishn/tikzcd-editor#10]
can you make tikzcd editor support double arrows, such as
 
![kwgyj](https://user-images.githubusercontent.com/3398776/31110079-617dfedc-a7d2-11e7-86e2-8f51c3d95b46.png)
and a more complicated example

![fxdog](https://user-images.githubusercontent.com/3398776/31110089-7731ffc6-a7d2-11e7-9f7b-9e892eacf4f7.png)

**Comment by yishn** [comment]
Displacement of arrows is currently not supported, but the second diagram should be creatable using tikzcd-editor.
