### ISSUE TITLE
Changing arrow size after placement

### ISSUE THREAD

**Issue by maxsnew** [yishn/tikzcd-editor#15]
Is there a way to stretch/shrink arrows after you've placed them?

**Comment by yishn** [comment]
No, is there any way to do that in tikzcd?

**Comment by maxsnew** [comment]
I'm not sure what you mean, in latex it would usually require adding newlines or &s.
In your `jsx-tikzcd` README example, this would correspond to changing the `from` or `to` properties of an `Edge`.

I naturally just tried to grab the end of an arrow and drag it to make it longer/shorter so that's what I'm imagining as a feature.
This would be very useful if you need to make an existing diagram larger/smaller without remaking the arrow altogether.

**Comment by heades** [comment]
I completely agree. I do this so often while writing papers with diagrams to things to fit.

**Comment by yishn** [comment]
@maxsnew You can drag the grid cells of the corresponding arrows around to make arrows longer/shorter.

**Comment by maxsnew** [comment]
@yishn ah great that does most of what I want. The only case it doesn't cover is when I want to shrink/stretch one arrow whose head is the same as another without affecting the other arrow.

You could work around this if you also had cut/paste, which is a feature I'd like even more.

**Comment by yishn** [comment]
> The only case it doesn't cover is when I want to shrink/stretch one arrow whose head is the same as another without affecting the other arrow.

Why would you want to do that? Don't you want the arrows to preserve source and target?

**Comment by maxsnew** [comment]
I can see wanting to do it if it was a mistake, or if you wanted to separate one diagram into two. But probably not a common thing to need.

**Comment by yishn** [comment]
Alright, I'm closing this as this has been resolved.
