### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by varkor** [yishn/tikzcd-editor#18]
One often want arrows from an object to itself (achieved with the tikzcd `loop` parameter), but it's only possible to draw arrows between different grid cells at the moment.

**Comment by yishn** [comment]
Can you post a simple LaTeX code snippet for loops? Do you have an idea how to let users create loops in tikzcd-editor? Currently, creating an arrow is only possible by dragging from one cell to another.

**Comment by varkor** [comment]
```latex
\begin{tikzcd}
A \arrow[loop]
\end{tikzcd}
```
Produces the following diagram:
![image](https://user-images.githubusercontent.com/3943692/33847334-0fad551a-dea2-11e7-8336-84d20824c4a4.png)
As for the interface, I think that not adding arrows when you haven't dragged between two cells is useful (for cancelling arrow placement), so perhaps a button that appears (similar to the "move object" handle) when arrow placement is selected, that adds a loop, would be simplest. The loop could then be manipulated with the existing arrow toolbar. It would be nice to also specify which side of the object the loop is drawn on, too.

**Comment by yishn** [comment]
Thank you for your input! Just out of curiosity's sake, can you rotate the loop in certain directions? For example, so that the "bump" points to the left?

**Comment by varkor** [comment]
`\arrow[loop left]` (or `above`/`below`/`right`) allows you to specify the direction, although specifying the direction a little more explicitly in the code output with `out=angle` and `in=angle` may result in slightly prettier loops. (I think these arguments come directly from TikZ, rather than tikz-cd).

**Comment by technicalguy** [comment]
I reckon the UI for loops and pullbacks (see issue #11) could be similar - a button and a way to change the position (e.g. a handle that can be dragged to rotate it to each of 4 directions [or more]).

**Comment by ericelliott** [comment]
This is a great suggestion. Identity arrows are very commonly needed to describe basic category theory principles and identity morphisms for axioms.

**Comment by ericelliott** [comment]
There is a [$200 bounty](https://www.bountysource.com/issues/52575605-loops) open for the developer who adds this feature.

**Comment by technicalguy** [comment]
Well I'll see if I can take a look at implementing this in the next week or two...

**Comment by varkor** [comment]
As there hadn't been much movement on this issue in a while, I went ahead and implemented the feature (pull request at https://github.com/yishn/tikzcd-editor/pull/35). I think the interface works quite well and it should definitely be sufficient for most of the use-cases of loops.

![image](https://user-images.githubusercontent.com/3943692/50121845-01a9f480-0252-11e9-938a-8c9863140239.png)
