### ISSUE TITLE
Multiple Selection Bug

### ISSUE THREAD

**Issue by maxsnew** [yishn/tikzcd-editor#19]
Selecting a square (to enter text) does not deselect the previous arrow you selected and anything you type in the square is also interpreted as an action on the arrow.

For instance, to reproduce
1. Make an arrow.
2. Click in the middle of a square, and a flashing cursor should appear.
3. Enter "R". An "R" appears in the square, and the arrow reverses.
4. Press backspace. The "R" and the arrow disappear.

I'm getting this behavior in both chromium and the latest firefox, both in "Arrow tool" mode and "Pan tool" mode.

**Comment by yishn** [comment]
Thank you for the report!
