### ISSUE TITLE
Diagrams with empty nodes produces invalid tikzcd code

### ISSUE THREAD

**Issue by maxsnew** [yishn/tikzcd-editor#20]
I'm getting some invalid tikzcd code when I have diagrams with "empty" nodes.

For instance an [arrow by itself](http://tikzcd.yichuanshen.de/#eyJub2RlcyI6W3sicG9zaXRpb24iOlswLDBdLCJ2YWx1ZSI6IiJ9LHsicG9zaXRpb24iOlsxLDBdLCJ2YWx1ZSI6IiJ9XSwiZWRnZXMiOlt7ImZyb20iOjAsInRvIjoxfV19) produces the code
```latex
\begin{tikzcd}
 \arrow[r] & 
\end{tikzcd}
```
and I get an error like this:
```
! Package pgf Error: No shape named tikz@f@5-1-2 is known.
...
l.441 I think the culprit is a tikzcd arrow in cell 1-1.
\errmessage ...currentrow -\tikzcd@currentcolumn }
                                                  
l.442 \end{tikzcd}
```

To fix this you can put in a dummy there like `{}`:
```latex
\begin{tikzcd}
{} \arrow[r] & {}
\end{tikzcd}
```

Here's a [bigger example](http://tikzcd.yichuanshen.de/#eyJub2RlcyI6W3sicG9zaXRpb24iOlswLDBdLCJ2YWx1ZSI6IkEifSx7InBvc2l0aW9uIjpbMiwwXSwidmFsdWUiOiJCIn0seyJwb3NpdGlvbiI6WzAsMl0sInZhbHVlIjoiQyJ9LHsicG9zaXRpb24iOlsyLDJdLCJ2YWx1ZSI6IkQifSx7InBvc2l0aW9uIjpbMSwxXSwidmFsdWUiOiJcXGFscGhhIFxcUmlnaHRhcnJvdyJ9LHsicG9zaXRpb24iOls0LDBdLCJ2YWx1ZSI6IkUifSx7InBvc2l0aW9uIjpbNCwyXSwidmFsdWUiOiJGIn0seyJwb3NpdGlvbiI6WzMsMV0sInZhbHVlIjoiXFxiZXRhIFxcUmlnaHRhcnJvdyJ9LHsicG9zaXRpb24iOls2LDBdLCJ2YWx1ZSI6IkEifSx7InBvc2l0aW9uIjpbOCwwXSwidmFsdWUiOiJFIn0seyJwb3NpdGlvbiI6WzYsMl0sInZhbHVlIjoiQyJ9LHsicG9zaXRpb24iOls4LDJdLCJ2YWx1ZSI6IkYifSx7InBvc2l0aW9uIjpbNywxXSwidmFsdWUiOiJcXGFscGhhO1xcYmV0YSBcXFJpZ2h0YXJyb3cifV0sImVkZ2VzIjpbeyJmcm9tIjowLCJ0byI6MSwidmFsdWUiOiJmIn0seyJmcm9tIjoyLCJ0byI6MywidmFsdWUiOiJnIn0seyJmcm9tIjowLCJ0byI6MiwidmFsdWUiOiJwIn0seyJmcm9tIjoxLCJ0byI6NSwidmFsdWUiOiJmJyJ9LHsiZnJvbSI6MywidG8iOjYsInZhbHVlIjoiZycifSx7ImZyb20iOjUsInRvIjo2LCJ2YWx1ZSI6InIifSx7ImZyb20iOjEsInRvIjozLCJ2YWx1ZSI6InEifSx7ImZyb20iOjgsInRvIjo5LCJ2YWx1ZSI6ImY7ZiciLCJsYWJlbFBvc2l0aW9uIjoibGVmdCJ9LHsiZnJvbSI6OCwidG8iOjEwLCJ2YWx1ZSI6InAifSx7ImZyb20iOjEwLCJ0byI6MTEsInZhbHVlIjoiZztnJyJ9LHsiZnJvbSI6OSwidG8iOjExLCJ2YWx1ZSI6InEifV19) that I was making where I put two diagrams side-by-side.
Here, the empty nodes aren't the source or target for anything, but they are still in the diagram.
I haven't looked at your representation, but I think the solution here would be to make sure that no nodes in the generated code are empty, where any cell within the bounding box of the whole diagram is going to be considered a node.

**Comment by yishn** [comment]
tikzcd-editor already includes `{}` for empty cells. Try empty your cache and reload the app; it should work correctly. The generated code of your 'bigger example' compiles without complaint.
