### ISSUE TITLE
Exporting diagrams as image? 

### ISSUE THREAD

**Issue by AesaKamar** [yishn/tikzcd-editor#25]
Is there any way that I can export the created diagrams in either a raster or vector format? 

I did see the companion project that lets you render these in JSX, and I realize this could probably be done in a LaTeX editor with some extensions, but I was wondering if there was a more convenient way.

**Comment by yishn** [comment]
The diagrams you see in the UI of tikzcd-editor aren't really that great. It's a fine visualization of the diagram, but we don't care about spacing, text overflows, proper layouting, or all the other things `tikz` will handle for you automatically. 

I recommend that you should let `tikz` and LaTeX do the drawing for you. You can use the `standalone` package to convert your diagrams into png.
