### ISSUE TITLE
Automated deployment or gh-pages deployment

### ISSUE THREAD

**Issue by cemulate** [yishn/tikzcd-editor#37]
It seems right now that the site living at [tikzcd.yichuanshen.de](http://tikzcd.yichuanshen.de) is not up to date with the latest release in this repo.

Since this is a static site, it _can_ be deployed on the repo's `gh-pages` branch, so it would be available at [yishn.github.io/tikzcd-editor](https://yishn.github.io/tikzcd-editor).

It's not exactly the most elegant thing in the world, but with the [gh-pages](https://www.npmjs.com/package/gh-pages) package, this could be as easy as adding the following npm script:

```
"deploy": "mkdir -p deploy; cp index.html deploy; cp favicon.ico deploy; cp -r dist deploy; cp -r css deploy; cp -r img deploy; gh-pages -d deploy"
```

Which would instantly update your gh-pages branch with the latest version of the site. I'm [doing this now](https://cemulate.github.com/tikzcd-editor) on my fork just as an example - If you want to remain hosting it wherever you are now, I'm sure a similar process could be automated without much trouble.

Before making a PR or anything, I wanted to open an issue and see if you had any thoughts on this.

**Comment by yishn** [comment]
The gh-pages package sure is pretty convenient. But I don't plan to change the URL of this application.

My hosted version is actually up to date with the [latest release in this repo](https://github.com/yishn/tikzcd-editor/releases/tag/v0.5.6). The master branch hasn't been released yet. I planned to devote more time to this project around Christmas last year, but I was busy with one or two of my other projects.

But hopefully I can polish the master branch soon, now that Chinese New Year has come and gone, and also review/merge all the PRs.

**Comment by cemulate** [comment]
Ah, my bad, I see now it's up to date with the latest release, just that the tip of master isn't released yet. Best of luck!
