### ISSUE TITLE
Arrow heads, tails aren't rendered in Safari

### ISSUE THREAD

**Issue by jonsterling** [yishn/tikzcd-editor#4]
This is awesome! I noticed that while everything seems to work great in Chrome, the arrow heads & tails aren't rendered in Safari (10.1).

It's not a big deal since it works fine in Chrome, so feel free to close if you're not interested in fixing.

**Comment by yishn** [comment]
I'm definitely interested in seeing this issue fixed. However, I don't have convenient access to Safari. If someone wants to investigate, I'll be happy to accept a pull request.

**Comment by Snark1994** [comment]
I'm getting a similar problem in Firefox 52.1.0 running on RedHat Linux. The body of the arrow renders fine, but heads and tails are rendered out of line and very small, so it look strange. It works fine in Chrome.
![screenshot 2017-08-31 scaled](https://user-images.githubusercontent.com/1990394/29920957-2aba310e-8e50-11e7-8c5a-d1f0cd75c139.png)

**Comment by yishn** [comment]
@Snark1994 I can't reproduce this behaviour on my Firefox 55.0.3 (32-bit) on Windows 10.
