### ISSUE TITLE
Using compression for shorter URLs?

### ISSUE THREAD

**Issue by gakada** [yishn/tikzcd-editor#49]
For example, with a library like https://github.com/polygonplanet/lzbase62 [`b64EncodeUnicode`](https://github.com/yishn/tikzcd-editor/blob/master/src/helper.js#L43) and `b64DecodeUnicode` can be defined just as

```js
export const b64EncodeUnicode = lzbase62.compress
export const b64DecodeUnicode = lzbase62.decompress
```

making URLs a bit shorter (something like 300 characters instead of 500, if I look at one example).

**Comment by yishn** [comment]
We're [already compressing links](https://github.com/yishn/tikzcd-editor/blob/master/src/components/App.js#L149) with the [`lz-string`](https://www.npmjs.com/package/lz-string) module for new diagrams.

**Comment by gakada** [comment]
I see, maybe just library difference then, I used lzbase62 some time ago and it seems a bit shorter, e.g.

https://tikzcd.yichuanshen.de/#N4Igdg9gJgpgziAXAbVABwnAlgFyxMJZARgBpiBdUkANwEMAbAVxiRAAUQBfU9TXfIRRkATFVqMWbABrdeIDNjwEiI8uPrNWiEAE05fJYNWkx1TVJ0AtAwv7KhyAAyknGydpABFbuJhQAc3giUAAzACcIAFskFxAcCCQyCS02NAB9YhBqBjoAIxgGdntjHXCsAIALHFsI6NjqBKQ1FMsFdJFayJjEZKbEAGZzDzZQ7JBcgqKSlTKK6q76xBb+odbPAMWegBZGxMQ4hiwwTyg6OEr-cYtPJi2kXfj9loKwKCQBuJu2AEcO+8Qj36yVe70QAFpPsNUjo-lkcvlCsUjLMQOUqjUuBQuEA

354

https://gakada.github.io/cd/#uDritefUVjrisStL2KtgfjZkZfexNDsIEItNsEritmRclV2OritBriuFsExfNsJEJxfLtAxfQsKxfNtJyBSsKxfLtIyBSxfMtK2fxODtVUXzrHtWifd2J4mritkf2H3NxoJtlri2MtcZexLEtURjY2xyaFxuN3cxuJthPsKxwDtSVe2nsSLIxqRsLxqMsJydEtR2stcAzqJritiZXYkyFJsFyGMzaDyGPtgyGbx4RzrL244rxgKxZDxgEsMxgKtXxeLyyDxePtWy3atNuF

274.

**Comment by yishn** [comment]
I think it is good enough. Changing the compression algorithm means we need to support three ways of parsing the URL if we want to remain backward compatible..
