### ISSUE TITLE
Render to SVG, PDF, PNG, etc.

### ISSUE THREAD

**Issue by okram** [yishn/tikzcd-editor#52]
I currently have this workflow.

1. Develop diagram in tikzcd-editor.
2. Copy/paste generated LaTeX source into LaTeXIt.
3. Export rendering as SVG to my project's images/ directory.
4. Save tikzcd-editor generated URL as a browser bookmark (as the saved "file").

Cutting the LaTeXIt step out would be helpful. Also, if a webservice was accessible for sending LaTeX source and getting back an SVG (that would be huge). I would then, in my AsciidoctorJ build file, check to see if any of the URLs have changed, if so, grab the latest rendering. That would remove a lot of human clickity-typity on my side.

I appreciate your project. Thank you.

**Comment by yishn** [comment]
Hi @okram, correctly rendering diagrams is definitely out of the scope of this project.
