### ISSUE TITLE
text inside squares?

### ISSUE THREAD

**Issue by Kreijstal** [yishn/tikzcd-editor#64]
I wanted to do a diagram on LTI systems, and this tool was almost perfect but, how can I make it do squares like

![image](https://user-images.githubusercontent.com/2415206/102269697-4c33d980-3f1d-11eb-912a-b07c2c339d55.png)

(Or if this is the wrong tool, what tool should I use instead?)

**Comment by yishn** [comment]
This tool is specifically designed to create tikzcd diagrams, specifically creating [commutative diagrams](https://en.wikipedia.org/wiki/Commutative_diagram). I do not know which tool to use to create a diagram on LTI systems.

**Comment by Kreijstal** [comment]
oh ok :(
